### ISSUE TITLE
SiteInfo Not working for a WML1.1 service

### ISSUE THREAD

**Issue by valentinedwv** [valentinedwv/CuahsiWOFSwagger#2]
My name is Yaping Xiao. I am a software engineer at CUAHSI, currently working on the project of harvesting the WaterOneFlow service metadata into Solr.

Basically, the harvesting of siteinfo is conducted via your RESTFUL WOF service at    http://hiscentralrest.azurewebsites.net/wateroneflow/siteinfo.  
However, the siteinfo request to GHCN network failed, as shown in the following url:
http://hiscentralrest.azurewebsites.net/wateroneflow/siteinfo?station=GHCN:AJ000037575&servUrl=http://hydrodata.info/GHCN/cuahsi_1_1.asmx&format=xml

When I request via the SOAP service of http://hydrodata.info/GHCN/cuahsi_1_1.asmx ,  GetSiteInfoObject() returns the requested siteinfo successfully.

FYI, here is the web.config I find in project CuahsiWOFSwagger (from GitHub)

```
    <binding name="WaterOneFlow" closeTimeout="00:03:00" receiveTimeout="00:05:00"
      sendTimeout="00:05:00" maxBufferPoolSize="2147483647" maxBufferSize="2147483647"
      maxReceivedMessageSize="2147483647" useDefaultWebProxy="true">
      <security mode="None" />
    </binding>

  <endpoint address="http://hydro10.sdsc.edu/lbrsdsc/cuahsi_1_1.asmx"
    binding="basicHttpBinding" bindingConfiguration="WaterOneFlow"
    contract="wof_1_1.WaterOneFlow" name="WaterOneFlow" />
```

I am puzzled why GHCN didn’t response through the RESTFUL service. Any suggestions are welcome. 

Thanks,
Yaping

**Comment by valentinedwv** [comment]
Fixed. Can you verify and close

**Comment by ypxiao** [comment]
Nope, still not working

**Comment by valentinedwv** [comment]
did you deploy it?

**Comment by ypxiao** [comment]
Hi David,
Thanks for checking. I grab the code and run the program from my local PC and it’s working properly.
I work from home today, and we’ll deploy it tomorrow.
Thank you for the help!

Cheers,
Yaping

**Comment by ypxiao** [comment]
working properly now!
